export interface seg_usuario{
  id_usuario?: number,
  id_departamento?: number,
  login?: string,
  password?: string,
  carnet?: number,
  nombre?: string,
  paterno?: string,
  materno?: string,
  direccion?: string,
  telefono?: number,
  fecha_vigente?: Date,
  foto?: string,
  fec_nacimiento?: Date,
  correo?: string,
  serie?: string,
  id_brigada?: number,
  remember_token?: string,
  apiestado?: string,
  usucre?: string,
  feccre?: Date,
  usumod?: string,
  fecmod?: Date,
  genero?: number,
  device_id?: string
}
